#!/usr/bin/env bash
set -euo pipefail
#
# generate.sh — Run on macOS to produce cross-platform files from source configs.
# Output: ~/platform/linux/*, ~/platform/macos/*, ~/platform/windows/*
#
# Usage:
#   chmod +x ~/bootstrap/generate.sh
#   ~/bootstrap/generate.sh [--tier desktop|laptop] [--dry-run] [--apply]
#
# Modes:
#   --dry-run   Write to /tmp, validate, show diff. No changes to ~/platform/.
#   --apply     Skip confirmation and write directly (use after a successful dry-run).
#   (default)   Write to /tmp first, validate, prompt to apply.
#
# Default tier: desktop (128 GB). Laptop tier adjusts .wslconfig + Ollama settings.

TIER="desktop"
DRY_RUN=false
AUTO_APPLY=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --tier) TIER="$2"; shift 2 ;;
    --dry-run) DRY_RUN=true; shift ;;
    --apply) AUTO_APPLY=true; shift ;;
    *) echo "Unknown arg: $1"; exit 1 ;;
  esac
done

PLATFORM_DIR="$HOME/platform"
STAGING_DIR=$(mktemp -d "/tmp/dotfiles-generate.XXXXXX")
# Always generate into staging first
OUTPUT_DIR="$STAGING_DIR/platform"
mkdir -p "$OUTPUT_DIR"/{macos,linux,windows}

echo "==> Generating platform files (tier: $TIER)"
echo "    Staging directory: $STAGING_DIR"
echo ""

# ─── platform/macos/extra ────────────────────────────────────────────────────
# Extract from current ~/.extra, stripping Android lines
echo "  → platform/macos/extra"
cat > "$OUTPUT_DIR/macos/extra" << 'MACOS_EXTRA'
# macOS PATH setup — auto-generated, edit source in ~/.extra then re-run generate.sh
BREW_PREFIX="$(brew --prefix 2>/dev/null || echo /opt/homebrew)"

PATH=$PATH:$BREW_PREFIX/lib
PATH=$PATH:/usr/local/bin
PATH=$PATH:/usr/bin
PATH=$PATH:/bin
PATH=$PATH:/usr/sbin
PATH=$PATH:/sbin

# VS Code
VSCODE_BIN="$(command -v code 2>/dev/null)"
if [ -z "$VSCODE_BIN" ]; then
  VSCODE_APP_BIN="/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
  [ -d "$VSCODE_APP_BIN" ] && PATH="$PATH:$VSCODE_APP_BIN"
fi

# gnu-sed (Homebrew)
GNU_SED_BIN="$BREW_PREFIX/opt/gnu-sed/libexec/gnubin"
[ -d "$GNU_SED_BIN" ] && PATH="$GNU_SED_BIN:$PATH"

export PATH
MACOS_EXTRA

# ─── platform/macos/aliases-local ────────────────────────────────────────────
echo "  → platform/macos/aliases-local"
cat > "$OUTPUT_DIR/macos/aliases-local" << 'MACOS_ALIASES'
# macOS-specific aliases
alias ls="ls -GFh"
alias vi="/usr/local/bin/vim"
alias brewup='brew update && brew upgrade && brew cleanup'
MACOS_ALIASES

# ─── platform/macos/env-local ────────────────────────────────────────────────
echo "  → platform/macos/env-local"
cat > "$OUTPUT_DIR/macos/env-local" << 'MACOS_ENV'
# macOS-specific environment variables
# (empty for now — add as needed)
MACOS_ENV

# ─── platform/linux/extra ────────────────────────────────────────────────────
echo "  → platform/linux/extra"
cat > "$OUTPUT_DIR/linux/extra" << 'LINUX_EXTRA'
# Linux/WSL2 PATH setup — auto-generated by generate.sh

PATH=$HOME/.local/bin:$PATH
PATH=$PATH:/usr/local/bin
PATH=$PATH:/usr/bin
PATH=$PATH:/bin
PATH=$PATH:/usr/sbin
PATH=$PATH:/sbin

# mise (version manager)
if [ -f "$HOME/.local/bin/mise" ]; then
  eval "$(~/.local/bin/mise activate zsh)"
fi

# VS Code (available via Windows PATH in WSL2 if "code" remote extension enabled)
# No manual PATH needed — WSL2 inherits Windows PATH for .exe

export PATH
LINUX_EXTRA

# ─── platform/linux/aliases-local ────────────────────────────────────────────
echo "  → platform/linux/aliases-local"
cat > "$OUTPUT_DIR/linux/aliases-local" << 'LINUX_ALIASES'
# Linux/WSL2-specific aliases — auto-generated by generate.sh

# ls — GNU coreutils uses --color instead of macOS -G
alias ls="ls --color=auto -Fh"
alias ll="ls -al"
alias vi="vim"

# Clipboard — bridge to Windows clipboard via WSL interop
alias pbcopy='clip.exe'
alias pbpaste='powershell.exe -command "Get-Clipboard"'

# Open — use Windows explorer from WSL
alias open='explorer.exe'

# System update (replaces 'brewup')
alias sysup='sudo apt update && sudo apt upgrade -y && sudo apt autoremove -y'
LINUX_ALIASES

# ─── platform/linux/env-local ────────────────────────────────────────────────
echo "  → platform/linux/env-local"
cat > "$OUTPUT_DIR/linux/env-local" << 'LINUX_ENV'
# Linux/WSL2 environment — auto-generated by generate.sh

# Locale (some Ubuntu installs are missing this)
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# Ollama — connect to Windows-native Ollama from WSL2
WIN_IP=$(grep -m1 nameserver /etc/resolv.conf | awk '{print $2}')
export OLLAMA_HOST="http://${WIN_IP}:11434"

# Quick LLM functions
ai()    { curl -s "$OLLAMA_HOST/api/generate" -d "{\"model\":\"llama3.3\",\"prompt\":\"$*\",\"stream\":false}" | python3 -c "import sys,json; print(json.load(sys.stdin)['response'])" ; }
codex() { curl -s "$OLLAMA_HOST/api/generate" -d "{\"model\":\"qwen2.5-coder:32b\",\"prompt\":\"$*\",\"stream\":false}" | python3 -c "import sys,json; print(json.load(sys.stdin)['response'])" ; }

# Git credential helper — configure manually post-bootstrap
# (e.g., gh auth setup-git, or git-credential-manager)
LINUX_ENV

# ─── platform/windows/wezterm.lua ────────────────────────────────────────────
echo "  → platform/windows/wezterm.lua"
cat > "$OUTPUT_DIR/windows/wezterm.lua" << 'WEZTERM'
-- WezTerm config — mirrors tmux C-a prefix and navigation binds
-- Auto-generated by generate.sh

local wezterm = require 'wezterm'
local act = wezterm.action
local config = wezterm.config_builder()

-- Visual
config.color_scheme = 'Molokai'
config.font = wezterm.font('MesloLGS NF')
config.font_size = 11.0
config.window_background_opacity = 0.95
config.hide_tab_bar_if_only_one_tab = true
config.window_padding = { left = 2, right = 2, top = 2, bottom = 2 }

-- Use C-a as leader (mirrors tmux prefix)
config.leader = { key = 'a', mods = 'CTRL', timeout_milliseconds = 1500 }

-- Default shell: WSL2 zsh
config.default_prog = { 'wsl.exe', '-d', 'Ubuntu-24.04', '--cd', '~', '-e', 'zsh', '-l' }

-- Tab bar styling (orange accent like tmux status bar)
config.colors = {
  tab_bar = {
    background = '#1c1c1c',
    active_tab = { bg_color = '#d75f00', fg_color = '#1c1c1c', intensity = 'Bold' },
    inactive_tab = { bg_color = '#3c3c3c', fg_color = '#808080' },
    new_tab = { bg_color = '#1c1c1c', fg_color = '#808080' },
  },
}

-- Key bindings (tmux-like)
config.keys = {
  -- Splits
  { key = '|', mods = 'LEADER|SHIFT', action = act.SplitHorizontal { domain = 'CurrentPaneDomain' } },
  { key = '-', mods = 'LEADER', action = act.SplitVertical { domain = 'CurrentPaneDomain' } },

  -- Navigation (vim-style)
  { key = 'h', mods = 'LEADER', action = act.ActivatePaneDirection 'Left' },
  { key = 'j', mods = 'LEADER', action = act.ActivatePaneDirection 'Down' },
  { key = 'k', mods = 'LEADER', action = act.ActivatePaneDirection 'Up' },
  { key = 'l', mods = 'LEADER', action = act.ActivatePaneDirection 'Right' },

  -- Resize (arrows)
  { key = 'LeftArrow',  mods = 'LEADER', action = act.AdjustPaneSize { 'Left', 5 } },
  { key = 'RightArrow', mods = 'LEADER', action = act.AdjustPaneSize { 'Right', 5 } },
  { key = 'UpArrow',    mods = 'LEADER', action = act.AdjustPaneSize { 'Up', 3 } },
  { key = 'DownArrow',  mods = 'LEADER', action = act.AdjustPaneSize { 'Down', 3 } },

  -- Tabs
  { key = 'c', mods = 'LEADER', action = act.SpawnTab 'CurrentPaneDomain' },
  { key = 'n', mods = 'LEADER', action = act.ActivateTabRelative(1) },
  { key = 'p', mods = 'LEADER', action = act.ActivateTabRelative(-1) },

  -- Close pane
  { key = 'x', mods = 'LEADER', action = act.CloseCurrentPane { confirm = true } },

  -- Zoom pane (like tmux C-a z)
  { key = 'z', mods = 'LEADER', action = act.TogglePaneZoomState },

  -- Copy mode (like tmux C-a [)
  { key = '[', mods = 'LEADER', action = act.ActivateCopyMode },

  -- Send literal C-a (press C-a twice)
  { key = 'a', mods = 'LEADER|CTRL', action = act.SendKey { key = 'a', mods = 'CTRL' } },
}

return config
WEZTERM

# ─── platform/windows/profile.ps1 ────────────────────────────────────────────
echo "  → platform/windows/profile.ps1"
cat > "$OUTPUT_DIR/windows/profile.ps1" << 'PWSH_PROFILE'
# PowerShell profile — auto-generated by generate.sh
# Symlink or copy to: $PROFILE (~\Documents\PowerShell\Microsoft.PowerShell_profile.ps1)

# Navigation (mirrors shell aliases)
function .. { Set-Location .. }
function ... { Set-Location ../.. }
function .... { Set-Location ../../.. }

# Utilities
function ll { Get-ChildItem -Force @args }
function which($cmd) { Get-Command $cmd -ErrorAction SilentlyContinue | Select-Object -ExpandProperty Source }
Set-Alias -Name cc -Value Clear-Host

# Jump into WSL2 dev session with tmux
function wsl-dev { wsl -d Ubuntu-24.04 -- zsh -c "cd ~/Development && tmux new-session -A -s dev" }

# Quick Ollama (native Windows)
function ai { ollama run llama3.3 @args }
function codex { ollama run qwen2.5-coder:32b @args }

# Scoop completions
Import-Module "$($(Get-Item $(Get-Command scoop.ps1 -ErrorAction SilentlyContinue).Path).Directory.Parent.FullName)\modules\scoop-completion" -ErrorAction SilentlyContinue
PWSH_PROFILE

# ─── platform/windows/wslconfig ──────────────────────────────────────────────
echo "  → platform/windows/wslconfig (tier: $TIER)"
if [[ "$TIER" == "desktop" ]]; then
cat > "$OUTPUT_DIR/windows/wslconfig" << 'WSLCONFIG_DESKTOP'
# .wslconfig — 128 GB Desktop Tier
# Copy to: C:\Users\<you>\.wslconfig
[wsl2]
memory=32GB
processors=12
swap=8GB
localhostForwarding=true
nestedVirtualization=true

[experimental]
autoMemoryReclaim=gradual
sparseVhd=true
WSLCONFIG_DESKTOP
else
cat > "$OUTPUT_DIR/windows/wslconfig" << 'WSLCONFIG_LAPTOP'
# .wslconfig — 64 GB Laptop Tier
# Copy to: C:\Users\<you>\.wslconfig
[wsl2]
memory=16GB
processors=8
swap=4GB
localhostForwarding=true

[experimental]
autoMemoryReclaim=gradual
sparseVhd=true
WSLCONFIG_LAPTOP
fi

# ─── Validation ───────────────────────────────────────────────────────────────
echo ""
echo "==> Validating generated output..."
ERRORS=0

# Check macOS extra has essential PATH components
if ! grep -q 'BREW_PREFIX' "$OUTPUT_DIR/macos/extra"; then
  echo "  ✗ FAIL: platform/macos/extra missing BREW_PREFIX"
  ERRORS=$((ERRORS + 1))
fi

# Check linux extra has PATH
if ! grep -q 'local/bin' "$OUTPUT_DIR/linux/extra"; then
  echo "  ✗ FAIL: platform/linux/extra missing ~/.local/bin PATH"
  ERRORS=$((ERRORS + 1))
fi

# Check wezterm.lua has leader key
if ! grep -q 'LEADER' "$OUTPUT_DIR/windows/wezterm.lua"; then
  echo "  ✗ FAIL: platform/windows/wezterm.lua missing LEADER key binding"
  ERRORS=$((ERRORS + 1))
fi

# Check wslconfig was generated
if [ ! -f "$OUTPUT_DIR/windows/wslconfig" ]; then
  echo "  ✗ FAIL: platform/windows/wslconfig not generated"
  ERRORS=$((ERRORS + 1))
fi

# Check all expected files exist
EXPECTED_FILES=(
  "macos/extra" "macos/aliases-local" "macos/env-local"
  "linux/extra" "linux/aliases-local" "linux/env-local"
  "windows/wezterm.lua" "windows/profile.ps1" "windows/wslconfig"
)
for f in "${EXPECTED_FILES[@]}"; do
  if [ ! -f "$OUTPUT_DIR/$f" ]; then
    echo "  ✗ FAIL: Missing expected file: platform/$f"
    ERRORS=$((ERRORS + 1))
  else
    echo "  ✓ platform/$f ($(wc -l < "$OUTPUT_DIR/$f") lines)"
  fi
done

# Compare against current ~/.extra if it exists (macOS sanity check)
if [ -f "$HOME/.extra" ]; then
  echo ""
  echo "==> Diff: current ~/.extra vs generated platform/macos/extra"
  echo "    (lines prefixed - are in your current file but NOT in the generated output)"
  diff --color=auto <(grep -v '^#\|^$' "$HOME/.extra" | sort) \
                    <(grep -v '^#\|^$' "$OUTPUT_DIR/macos/extra" | sort) || true
fi

echo ""
if [ $ERRORS -gt 0 ]; then
  echo "==> ✗ VALIDATION FAILED ($ERRORS errors). Fix issues before applying."
  echo "    Staged output preserved at: $STAGING_DIR"
  exit 1
fi

echo "==> ✓ All validations passed."
echo ""

# ─── Apply or stop ────────────────────────────────────────────────────────────
if [ "$DRY_RUN" = true ]; then
  echo "==> DRY RUN complete. No changes made to ~/platform/."
  echo "    Review staged output at: $STAGING_DIR"
  echo ""
  echo "    To inspect individual files:"
  echo "      cat $STAGING_DIR/platform/macos/extra"
  echo "      cat $STAGING_DIR/platform/linux/env-local"
  echo ""
  echo "    To apply after review:"
  echo "      ~/bootstrap/generate.sh --tier $TIER --apply"
  exit 0
fi

if [ "$AUTO_APPLY" = false ]; then
  echo "==> Ready to write to ~/platform/. This will overwrite existing files."
  echo "    Staged output: $STAGING_DIR/platform/"
  echo ""
  read -rp "    Apply? [y/N] " confirm
  if [[ ! "$confirm" =~ ^[Yy]$ ]]; then
    echo "    Aborted. Staged output preserved at: $STAGING_DIR"
    exit 0
  fi
fi

# Apply — copy staging to real location
mkdir -p "$PLATFORM_DIR"/{macos,linux,windows}
cp -R "$STAGING_DIR/platform/"* "$PLATFORM_DIR/"
rm -rf "$STAGING_DIR"

echo ""
echo "==> Applied. Generated files in ~/platform/"
echo "    Review, then commit:"
echo "      config add platform/"
echo "      config commit -m 'Add cross-platform dotfiles'"
echo ""
echo "==> Next steps:"
echo "    1. Update ~/.zshrc with the platform detection block (see plan section 1.3)"
echo "    2. Move macOS-specific content out of shared .aliases/.functions/.extra"
echo "    3. Run: config add .aliases .functions .zshrc && config commit"
