# PowerShell profile — auto-generated by generate.sh
# Symlink or copy to: $PROFILE (~\Documents\PowerShell\Microsoft.PowerShell_profile.ps1)

# Navigation (mirrors shell aliases)
function .. { Set-Location .. }
function ... { Set-Location ../.. }
function .... { Set-Location ../../.. }

# Utilities
function ll { Get-ChildItem -Force @args }
function which($cmd) { Get-Command $cmd -ErrorAction SilentlyContinue | Select-Object -ExpandProperty Source }
Set-Alias -Name cc -Value Clear-Host

# Jump into WSL2 dev session with tmux
function wsl-dev { wsl -d Ubuntu-24.04 -- zsh -c "cd ~/Development && tmux new-session -A -s dev" }

# Quick Ollama (native Windows)
function ai { ollama run llama3.3 @args }
function codex { ollama run qwen2.5-coder:32b @args }

# Scoop completions
Import-Module "$($(Get-Item $(Get-Command scoop.ps1 -ErrorAction SilentlyContinue).Path).Directory.Parent.FullName)\modules\scoop-completion" -ErrorAction SilentlyContinue
