-- WezTerm config — mirrors tmux C-a prefix and navigation binds
-- Auto-generated by generate.sh

local wezterm = require 'wezterm'
local act = wezterm.action
local config = wezterm.config_builder()

-- Visual
config.color_scheme = 'Molokai'
config.font = wezterm.font('MesloLGS NF')
config.font_size = 11.0
config.window_background_opacity = 0.95
config.hide_tab_bar_if_only_one_tab = true
config.window_padding = { left = 2, right = 2, top = 2, bottom = 2 }

-- Use C-a as leader (mirrors tmux prefix)
config.leader = { key = 'a', mods = 'CTRL', timeout_milliseconds = 1500 }

-- Default shell: WSL2 zsh
config.default_prog = { 'wsl.exe', '-d', 'Ubuntu-24.04', '--cd', '~', '-e', 'zsh', '-l' }

-- Tab bar styling (orange accent like tmux status bar)
config.colors = {
  tab_bar = {
    background = '#1c1c1c',
    active_tab = { bg_color = '#d75f00', fg_color = '#1c1c1c', intensity = 'Bold' },
    inactive_tab = { bg_color = '#3c3c3c', fg_color = '#808080' },
    new_tab = { bg_color = '#1c1c1c', fg_color = '#808080' },
  },
}

-- Key bindings (tmux-like)
config.keys = {
  -- Splits
  { key = '|', mods = 'LEADER|SHIFT', action = act.SplitHorizontal { domain = 'CurrentPaneDomain' } },
  { key = '-', mods = 'LEADER', action = act.SplitVertical { domain = 'CurrentPaneDomain' } },

  -- Navigation (vim-style)
  { key = 'h', mods = 'LEADER', action = act.ActivatePaneDirection 'Left' },
  { key = 'j', mods = 'LEADER', action = act.ActivatePaneDirection 'Down' },
  { key = 'k', mods = 'LEADER', action = act.ActivatePaneDirection 'Up' },
  { key = 'l', mods = 'LEADER', action = act.ActivatePaneDirection 'Right' },

  -- Resize (arrows)
  { key = 'LeftArrow',  mods = 'LEADER', action = act.AdjustPaneSize { 'Left', 5 } },
  { key = 'RightArrow', mods = 'LEADER', action = act.AdjustPaneSize { 'Right', 5 } },
  { key = 'UpArrow',    mods = 'LEADER', action = act.AdjustPaneSize { 'Up', 3 } },
  { key = 'DownArrow',  mods = 'LEADER', action = act.AdjustPaneSize { 'Down', 3 } },

  -- Tabs
  { key = 'c', mods = 'LEADER', action = act.SpawnTab 'CurrentPaneDomain' },
  { key = 'n', mods = 'LEADER', action = act.ActivateTabRelative(1) },
  { key = 'p', mods = 'LEADER', action = act.ActivateTabRelative(-1) },

  -- Close pane
  { key = 'x', mods = 'LEADER', action = act.CloseCurrentPane { confirm = true } },

  -- Zoom pane (like tmux C-a z)
  { key = 'z', mods = 'LEADER', action = act.TogglePaneZoomState },

  -- Copy mode (like tmux C-a [)
  { key = '[', mods = 'LEADER', action = act.ActivateCopyMode },

  -- Send literal C-a (press C-a twice)
  { key = 'a', mods = 'LEADER|CTRL', action = act.SendKey { key = 'a', mods = 'CTRL' } },
}

return config
